# Generated by Django 5.2.4 on 2025-07-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField()),
                ('duration_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('week_day', models.CharField(max_length=15)),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
